apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gg0o5oep7-java-springboot
  janus-idp.io/tekton: gg0o5oep7-java-springboot
  backstage.io/kubernetes-id: gg0o5oep7-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gg0o5oep7-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
